logging:
  pattern:
    console: "[Kafka Core Consumer] %clr(%d{HH:mm:ss.SSS}){faint} %clr(${LOG_LEVEL_PATTERN:%5p}) %clr(---){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %clr(%t){magenta} %clr(:){faint} %m%n${LOG_EXCEPTION_CONVERSION_WORD:%wEx}"

spring:
    application:
        name: Kafka-Consumer
    main:
        banner-mode: off
        log-startup-info: false
    kafka:
      listener:

        ack-mode: batch
#       ack-mode: manual
#       ack-mode: count
#       ack-mode: time
#       ack-mode: count_time
        ack-count: 10 #Esta configuración debe ir si tenemos ack mode en count.
      consumer:
        auto-offset-reset: earliest
        max-poll-records: 7   #Esta configuración debe ir si tenemos ack-mode en batch.
      bootstrap-servers: localhost:9092
    jackson:
      date-format: yyyy-MM-dd
      